name: Deploy Welcome Lambda Function

on:
  push:
    branches:
      - welcome-lambda
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and create deployment package
        working-directory: ./lambdas/welcome_function
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t package
          fi
          mkdir -p package
          cp welcome_function.py package/
          cd package
          zip -r ../function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name welcome-lambda \
            --zip-file fileb://lambdas/welcome_function/function.zip
